### ISSUE TITLE
How to close expanded list without click?

### ISSUE THREAD

**Issue by JinSB** [h6ah4i/android-advancedrecyclerview#110]
Some cases I want to expand only one list item. Other expanded list must be close when I expand one list or sometimes expand/close all list. Are there any API for this case?

**Comment by JinSB** [comment]
I think this issue is duplicated. Is it possible to know when the 0.8.0 release plan?

Thank you.

**Comment by h6ah4i** [comment]
Hi. I'm planning to release 0.8.0 at the end of this month.

The v0.8.0 will include `expandAll()` and `collapseAll()` methods, but maybe it will not help to achieve the behavior which you want (because those methods invokes `notifyDataSetChanged()` internally).

I recommend you to use `expandGroup()` and `collapseGroup()` methods they are ready in current library instead.

**Comment by JinSB** [comment]
Hi

Where do i have implement "group onclicklistener"?
I tested collapseGroup method it works fine.

Thanks.

**Comment by h6ah4i** [comment]
Hi. 

Make the `onCheckCanExpandOrCollapseGroup()` method always return `false`, it will prevent to expand/collapse automatically when clicking a group item. Then, you can set your own click listener in the `onCreateGroupViewHolder()` or in the `onBindGroupViewHolder()` method.

The ["Expandable (Add/Remove)" demo](https://github.com/h6ah4i/android-advancedrecyclerview/blob/a8d755dc4d6f9ef21f0cdeae3d91b910c0290219/example/src/main/java/com/h6ah4i/android/example/advrecyclerview/demo_e_add_remove/MyAddRemoveExpandableItemAdapter.java#L214) implements custom click event handling. Please refer to its implementation.

Related issue: #11 

Thanks.
