### ISSUE TITLE
Expand Indicator Not Animating on Android 6.0

### ISSUE THREAD

**Issue by stephenmcbride** [h6ah4i/android-advancedrecyclerview#149]
Only the expand animator (MorphButton) in the first row animates, the ones in the other rows do not animate. Reproduced on Nexus 5X and Genymotion Nexus 5X on sample downloaded from Play Store and on sample built from master.

**Comment by h6ah4i** [comment]
Confirmed. It looks like a vector-compat library issue. I will try to implement a workaround later. Thanks! 

ref.)  https://github.com/wnafee/vector-compat/issues/29

**Comment by h6ah4i** [comment]
Hi. I have just released v0.8.5. I have changed the indicator implementation not to use the vector-compat library.

- vector-compat is incompatible with the latest Gradle plugin
- vector-compat is not working properly on Marshmallow

I decided to use native VectorDrawable since v0.8.5 demo app, so indicators will not animate on KitKat or older Android.

**Comment by stephenmcbride** [comment]
Cool thanks for following up on this issue and for your work on this lib!
