### ISSUE TITLE
parallax background feature

### ISSUE THREAD

**Issue by jjhesk** [h6ah4i/android-advancedrecyclerview#20]
does it have any feature that i can do parallax background while it item is scolling?

**Comment by h6ah4i** [comment]
Hi. Do you mean the feature like the SoundCloud app? (https://www.youtube.com/watch?v=bfOuWpPkA6Q)

Sorry, this library does not have such feature for now but it seems not difficult because `RecyclerView` provides enough features to handle that.

Solution 1:
 - Use `RecyclerView.ItemDecoration` + custom item view

Solution 2:
- Use `RecyclerView.OnScrollListener` + custom item view
