### ISSUE TITLE
EditText can not show my expect text

### ISSUE THREAD

**Issue by lujianzhi** [h6ah4i/android-advancedrecyclerview#226]
I add edittext in my all child items ,and when i am scrolling these items, i found my edittext's text was losing their position.I add edittext into your demo,it happens again,is it a bug?
for example:
 childposition:0     edittext:"hello"
 childposition:1     edittext:"world"
after my scroll,it comes to
 childposition:0     edittext:"hello"
 childposition:1     edittext:"hello"
or
 childposition:0     edittext:"world"
 childposition:1     edittext:"hello"
or other conditions.
why is happens?it confused me a long time.

**Comment by h6ah4i** [comment]
Hi. That comes from RecyclerView's mechanism (not a bug of RecyclerView or this library). Each item views are recycled if they go out of the screen, and collected views will be re-used for newly visible items. It happens when you scroll the RecyclerView. That is why you did see duplicate "hello" items and item position swappings.

What you have to do is save EditText's state in the [`onViewRecycled()`](http://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#onViewRecycled(VH)) method, and restore its state in the [`onBindViewHolder()`](http://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#onBindViewHolder(VH, int)).

**Comment by lujianzhi** [comment]
But my Button's text don't change.I set Button's text just like EditText's.On their Listeners,I put the new value into a "PersonBeen"(JavaBeen) by setButtonStr() method and setEditStr() method.And in onBindChildViewHolder(),I put value into Button and EdtiText by getButtonStr() and getEditStr().Only EditTexts change...
I am a new coder,your library is excellent,so my problem maybe silly...

**Comment by lujianzhi** [comment]
I had found way to solve this problem.

**Comment by JakeWoki** [comment]
@lujianzhi @h6ah4i How to do.

**Comment by lujianzhi** [comment]
@JakeWoki 你也是中国人吧~不知道你解决没有，下面是我总结的：
EditText数值出现错位问题
解决方法:
  在EditText所在的ViewHolder中自己实现一个TextWather，该TextWather中写方法传入对应位置的Item或者传入实时的position或是Item。并在此TextWatcher中进行操作
例如:
  pubic class MyChildViewHolder extends MyBaseViewHolder{
//控件定义

public MyChildViewHolder (…){
  //…控件初始化
  //为EditText设置自定义的MyTextWatcher
}

private class MyTextWatcher extends TextWatcher{
  //变量

  //绑定position或是item
  public void updateItem(…){…}
  public void updatePosition(…){…}

  //重写父类方法
}
}
