### ISSUE TITLE
Example project: ExpandableItemIndicator.java onInit method - wrong minimal api level for animated indicator

### ISSUE THREAD

**Issue by ardmn** [h6ah4i/android-advancedrecyclerview#271]
Source code from example project:

```java
protected void onInit(Context context, AttributeSet attrs, int defStyleAttr) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            // NOTE: Use animated indicator only on API level 16+ due to performance reason.
            mImpl = new ExpandableItemIndicatorImplAnim();
        } else {
            mImpl = new ExpandableItemIndicatorImplNoAnim();
        }
        mImpl.onInit(context, attrs, defStyleAttr, this);
    }
```

but animated-vector  element of ic_expand_more_to_expand_less.xml and ic_expand_less_to_expand_more.xml available only from 21 api level

**Comment by h6ah4i** [comment]
Hi. I believe that is not a bug. Have you tried adding the following setting to your `build.gradle`?

```gradle
android {
    defaultConfig {
        vectorDrawables.useSupportLibrary = true
    }
}
```

In the example app, it uses `AnimatedVectorDrawableCompat` for animated indicator. Therefore the animation will work on API level 11 or later, but I decided to enable it only for API level 16 or later due to performance reason of both hardware and Android platform.

---

NOTE:

I made a small modification to `ExpandableItemIndicator` in the commit d2e954d. It is just a small refactoring, I added `shouldUseAnimatedIndicator()` method which determines whether to use animations. Override or tweak this method according to your decision.

```java
    protected boolean shouldUseAnimatedIndicator(Context context, AttributeSet attrs, int defStyleAttr) {
        return Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN;
    }

    protected void onInit(Context context, AttributeSet attrs, int defStyleAttr) {
        if (shouldUseAnimatedIndicator(context, attrs, defStyleAttr)) {
            mImpl = new ExpandableItemIndicatorImplAnim();
        } else {
            mImpl = new ExpandableItemIndicatorImplNoAnim();
        }
        mImpl.onInit(context, attrs, defStyleAttr, this);
    }
```

**Comment by ardmn** [comment]
Sorry. You are right . Thank you :)

**Comment by ray-pixar** [comment]
I'm trying to write my own sample but "ExpandableItemIndicatorImplAnim" animation for Lollipop and above dosen't work, thought it changes the icon without anim.  Is there any piece of code that I'm missing?
