### ISSUE TITLE
Drag doesn't work properly on some areas of drag_handle

### ISSUE THREAD

**Issue by piotrwojtowicz** [h6ah4i/android-advancedrecyclerview#318]
You can reproduce it on your demo app. Seems that some areas of drag_handle doesn't trigger dragging. Please try starting dragging on emulator (I used Genymotion) with mouse (to have precise clicks) and drag_handle corners (i.e. for 1st, middle and last visible items in list).

**Comment by h6ah4i** [comment]
Hi. The behavior is by design for now.

This library assumes that user want to start dragging an item if finger moved more than **Touch slop** (`=getScaledTouchSlop()`) distance. So this library checks twice whether the finger is inside of the drag handle; 1. ACTION_DOWN, 2. moved more than *touch slop* pixels.

![image](https://cloud.githubusercontent.com/assets/2552365/20079898/4506a434-a58a-11e6-94fb-0494d9819f84.png)

**Comment by piotrwojtowicz** [comment]
Thank you, now it's clear :)
