### ISSUE TITLE
Recreate the animation that occurs after swipe to remove group 

### ISSUE THREAD

**Issue by ibcurly** [h6ah4i/android-advancedrecyclerview#322]
In your "Expandable + Draggable + Swipeable" example, in the function "GroupSwipeRightResultAction" The group is swiped out of view revealing the blue view underneath. That blue view gets a shrinking animation, and then the group is deleted.

If i use the same swipe to delete function in my app, the shrinking animation occurs like in the example.
If i swipe the group and pin it to the side to reveal a delete button, and then use the delete button to remove the group, the entire group disappears with no shrinking animation of the underlying view.
**How can i get that shrinking animation when deleting a group using a button?**

I checked the code and it seems they have the same two function calls:
` mAdapter.mProvider.removeGroupItem(mGroupPosition);
  mAdapter.mExpandableItemManager.notifyGroupItemRemoved(mGroupPosition);`

Am i missing something? 
Thank you for your time.

**Comment by h6ah4i** [comment]
Hi. 

> How can i get that shrinking animation when deleting a group using a button?

The shrinking animation is only applied only when swipe dismiss action. However, you can use the same effect by using an internal class of this library.

#### 1. Copy the `RemovingItemDecorator` class to your app
Since the `RemovingItemDecorator` is a package scope class, you need to make a copy to use it.

- [RemovingItemDecorator ](https://github.com/h6ah4i/android-advancedrecyclerview/blob/0.10.0/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/swipeable/RemovingItemDecorator.java)

Then, modify the `start()` method to fix compilation error

```java
// final View containerView = SwipeableViewHolderUtils.getSwipeableContainerView(mSwipingItem);
final View containerView = ((SwipeableItemViewHolder) mSwipingItem).getSwipeableContainerView();
```

#### 2. Use `RemovingItemDecorator`

```java
// Remove the group item (position = groupPosition)
getDataProvider().removeGroupItem(groupPosition);
mRecyclerViewExpandableItemManager.notifyGroupItemRemoved(groupPosition);

// Apply removing item effect
RecyclerView.ViewHolder vh = mRecyclerView.findContainingViewHolder(v);
long moveDuration = mRecyclerView.getItemAnimator().getMoveDuration();
long removeDuration = mRecyclerView.getItemAnimator().getRemoveDuration();
RemovingItemDecorator decorator = new RemovingItemDecorator(
        mRecyclerView, vh, SwipeableItemConstants.RESULT_SWIPED_LEFT, moveDuration, removeDuration);
decorator.start();
```

**Comment by ibcurly** [comment]
Thank you for your specific response, I got it working first try :)
