### ISSUE TITLE
Draggable recyclerview inside draggable recyclerview 

### ISSUE THREAD

**Issue by zhenghuanpeng1992** [h6ah4i/android-advancedrecyclerview#327]
Draggable recyclerview inside draggable recyclerview , the inside recyclerview's adapter's onCheckCanStartDrag method has called and return true. But inside recyclerview's adapter item can't start drag, how can i sovle this problem? thx.

**Comment by h6ah4i** [comment]
Hi. Thanks for reporting the issue. I will investigate it within few days.

**Comment by zhenghuanpeng1992** [comment]
@h6ah4i Thank you for your reply. Now for my tentative solution, if the child's onCheckCanStartDrag method returns true then I have to disable the parent's(recyclerview) onInterceptTouchEvent method.

**Comment by h6ah4i** [comment]
@zhenghuanpeng1992 Hi. Try adding `dragDropManager.setInitiateOnTouch(true)` to solve the issue.

---

**Additional info.**
I noticed that this issue is only present if there is a nested RecyclerView and it has the same layout direction of its parent. If the layout direction is different, no need to call `setInitiateOnTouch()`. 

The `setInitiateOnTouch(true)` method call disables touch slop checking, so dragging start immediately after `onCheckCanStartDrag()` called.

**Comment by zhenghuanpeng1992** [comment]
@h6ah4i dragDropManager.setInitiateOnTouch(true)  solved this issue, thanks.
