### ISSUE TITLE
Drag animation does not work properly.

### ISSUE THREAD

**Issue by zeroarst** [h6ah4i/android-advancedrecyclerview#337]
Video: https://sendvid.com/q83gao0p

The data re-positioning is working, just the animation itself seems to use the default RecycleView's item moving animation, instead of this lib's, which the item should just drop to the new position, not start over the animation.

I scratched my head trying to figure out what is the problem...but still cannot find it. Please help..

fragment:
```
if (mRvAdpt == null)
    mRvAdpt = new MultiImageSourcesRecycleViewAdapter(getActivity());
mRvAdpt.setData(mMultiImgSources.getSources());
if (mLayoutMgr == null)
    mLayoutMgr = new LinearLayoutManager(getActivity(), LinearLayoutManager.VERTICAL, false);
mRv.setLayoutManager(mLayoutMgr);
if (mRvDragDropMgr == null)
    mRvDragDropMgr = new RecyclerViewDragDropManager();
if (mWrappedAdapter == null)
    mWrappedAdapter = mRvDragDropMgr.createWrappedAdapter(mRvAdpt);
mRv.setAdapter(mWrappedAdapter);
mRv.setItemAnimator(new DraggableItemAnimator());
mRvDragDropMgr.attachRecyclerView(mRv);
```

adapter:
```
@Override
public void onMoveItem(int fromPosition, int toPosition) {
    if (fromPosition == toPosition) {
        return;
    }

    final ImageSource item = getData().remove(fromPosition);

    getData().add(toPosition, item);

    notifyItemMoved(fromPosition, toPosition);
}
```

**Comment by zeroarst** [comment]
I fixed it. Turned out that I only returned in `getItemId` I returned item position instead of unique id. I changed to `item.hashCode()` then worked.

**Comment by h6ah4i** [comment]
@zeroarst Hi. Sorry for the late reply. I will close this issue because you have already fixed it.

---

Also, I put some links here for someone also troubled with the same issue.

**Tutorial:**
- [Drag & Drop - Step 1. Make the adapter supports stable IDs](http://h6ah4i.com/android-advancedrecyclerview/draggable/#step-1-make-the-adapter-supports-stable-ids)

**Same/Related issue reports:**
- [Repeated animation problem #5](https://github.com/h6ah4i/android-advancedrecyclerview/issues/5)
- [Unnecessary animation on drag #83](https://github.com/h6ah4i/android-advancedrecyclerview/issues/83)
- [[HELP] Swipe animation not like example #199](https://github.com/h6ah4i/android-advancedrecyclerview/issues/199)
- [Position Changing Between List Item #22](https://github.com/h6ah4i/android-advancedrecyclerview/issues/22)
