### ISSUE TITLE
Notify Item Insert/Remove for ExpandableRecyclerView

### ISSUE THREAD

**Issue by JSteveNunez** [h6ah4i/android-advancedrecyclerview#34]
How would I notify the adapter that a child item whose parent isn't expanded was removed? Since the parent is not expanded that child item does not have a position. I do not really want to use notifyDataSetChanged() as this is not efficient when i have a large dataSet. I tried notifying the wrappedAdapter but that seems to not work.

**Comment by marcusforsberg** [comment]
I have the same issue, also when it comes to adding or even updating a child of a hidden group. Any tips?

**Comment by h6ah4i** [comment]
Has been fixed in 0.7.3.  Use these methods and also check the "Expandable (Add/Remove items)" example.

- [`RecyclerViewExpandableItemManager.notifyGroupItemInserted()`](https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/expandable/RecyclerViewExpandableItemManager.java#L657)
- [`RecyclerViewExpandableItemManager.notifyGroupItemRangeInserted()`](https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/expandable/RecyclerViewExpandableItemManager.java#L676)
- [`RecyclerViewExpandableItemManager.notifyChildItemInserted()`](https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/expandable/RecyclerViewExpandableItemManager.java#L695)
- [`RecyclerViewExpandableItemManager.notifyChildItemRangeInserted()`](https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/expandable/RecyclerViewExpandableItemManager.java#L715)
- [`RecyclerViewExpandableItemManager.notifyGroupItemRemoved()`](https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/expandable/RecyclerViewExpandableItemManager.java#L732)
- [`RecyclerViewExpandableItemManager.notifyGroupItemRangeRemoved()`](https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/expandable/RecyclerViewExpandableItemManager.java#L749)
- [`RecyclerViewExpandableItemManager.notifyChildItemRemoved()`](https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/expandable/RecyclerViewExpandableItemManager.java#L767)
- [`RecyclerViewExpandableItemManager.notifyChildItemRangeRemoved()`](https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/expandable/RecyclerViewExpandableItemManager.java#L785)
