### ISSUE TITLE
Snapping on first item with draggable grid

### ISSUE THREAD

**Issue by Sroka** [h6ah4i/android-advancedrecyclerview#389]
There is visible snapping instead of smooth animation when moving the item from second visible row to the first visible row's first item.

It can be reproduced on version 10.06

Here is a gif with reproduction of this behavior in my app but I can see the same behavior in sample app from this repo
https://gfycat.com/ThatComposedGrub

**Comment by h6ah4i** [comment]
@Sroka Hi. Thanks for reporting the issue.

Unfortunately, that is an intended behavior of `RecyclerView` so it will never be fixed. Please refer to the following issue tracker thread.

- [Issue 37018279 - Inconsistent behavior produced by mAdapter.notifyItemMoved(indexA,indexB);](https://issuetracker.google.com/issues/37018279)

### Possible workaround
Add a non-visible dummy header item to the list. However, this workaround is not perfect because the issue also happens when the non-first row is the first visible one.

**Comment by Sroka** [comment]
@h6ah4i Thank you for quick response. This workaround seems like a good idea. I have fixed column length so maybe I can try to insert this dummy item every two normal items.
