### ISSUE TITLE
Scroll to the last child if it is offscreen

### ISSUE THREAD

**Issue by Kuci** [h6ah4i/android-advancedrecyclerview#60]
When you expand a group and its last child is not visible, RecyclerView should scroll to the last child to make it visible, exactly as ExpandableListView does it.

**Comment by h6ah4i** [comment]
I think automatic scrolling when expanding a group item should not be performed by this library. That should be implemented by app developers in order to allow app specific behavior.

These methods can be used to calculate the scroll offset and to perform scrolling.
- `LinearLayoutManager. scrollToPositionWithOffset()`
- `LinearLayoutManager. findFirstVisibleItemPosition()`
- `LinearLayoutManager. findLastVisibleItemPosition()`
- `LinearLayoutManager. findFirstCompletelyVisibleItemPosition()`
- `LinearLayoutManager. findLastCompletelyVisibleItemPosition()`
- `RecyclerView. scrollBy()`
- `RecyclerView. smoothScrollBy()`
- `RecyclerView. scrollToPosition()`
- `RecyclerView. smoothScrollToPosition()`

However I am going to update the demo code and add a sample implementation, so app developers can refer that.

**Comment by Kuci** [comment]
I see it like this: Does ExpandableListView do it ? Then ExpandableRecyclerView should do it as well. I think the vast majority of developers will not try to get rid of this effect, but if you think so, then I think it would be a better idea to turn it on by default and add an option to turn it off.

**Comment by h6ah4i** [comment]
I decided to add `scrollToGroup()` method to `RecyclerViewExpandableItemManager` on next update. Please call this method when group item is expanded.

Also, I created a feature branch and the method has already been implemented. You can port it to your project with a little modifications.

- https://github.com/h6ah4i/android-advancedrecyclerview/blob/feature/scroll_on_group_expand/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/expandable/RecyclerViewExpandableItemManager.java#L816

**Comment by h6ah4i** [comment]
0.8.0 is out.
