### ISSUE TITLE
Can not refresh expandable adapter

### ISSUE THREAD

**Issue by sergeyfitis** [h6ah4i/android-advancedrecyclerview#63]
Hi. How correctly to refresh expandable adapter when count of group's children has changed?
Because when I do notifyDataSetChanged it updates only groups but not group's children.

**Comment by h6ah4i** [comment]
Already fixed in 0.7.3. 

Use [`RecyclerViewExpandableItemManager.notifyChildItemRangeRemoved(int groupPosition, int childPositionStart, int itemCount)`](https://github.com/h6ah4i/android-advancedrecyclerview/blob/0.7.3/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/expandable/RecyclerViewExpandableItemManager.java#L785).

**Comment by sergeyfitis** [comment]
Thank you. :+1:
