### ISSUE TITLE
Button Clicking and expanding problem

### ISSUE THREAD

**Issue by pecabum** [h6ah4i/android-advancedrecyclerview#73]
Hello , i have a button , but when it's clicked the view get expanded instead of doing the button action.

**Comment by h6ah4i** [comment]
Need to modify the  `onCheckCanExpandOrCollapseGroup()` method.

### Solution 1

Make the method returns `false` if the touched positon is on the button.

- example; excluding mDragHandle
https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/example/src/main/java/com/h6ah4i/android/example/advrecyclerview/demo_eds/MyExpandableDraggableSwipeableItemAdapter.java#L293


### Solution 2

Make the method always returns `false` in order to disable default collapse/expand behavior. Set `OnClickListener` to item views and use `RecyclerViewExpandableItemManager.expandGroup()/collapaeGroup()`.

- 
related issue: #11
